### ISSUE TITLE
MetaMask : Structure the Functions into different files to avoid cluttering

### ISSUE THREAD

**Issue by CodeMongerrr** [CodeMongerrr/Certicryped#1]

**Comment by CodeMongerrr** [comment]
In the client/src/App.js you can see a lot of functions I want someone to make a new folder in the src directory and make js files in the folder I want atleast one js file named web3_func that has these 4 functions loadWeb3, loadContract, signMessage, connect. 

Clone the repo start the client and backend and submit a pull request if nothing breaks

**Comment by KrownWealth** [comment]
Hi CodeMongerr,

I would love to work on this issue, make a new folder and create a single function file inside that encapsulate all the  above-mentioned functions.

**Comment by CodeMongerrr** [comment]
It would be great if you would work on the issue

**Comment by KrownWealth** [comment]
Awesome, I will

**Comment by KrownWealth** [comment]
I've done the necessary steps in cloning and creating a branch before starting to fix the changes.

But right now am curious as  npm start command didn't work on loading the local server of the project.

Is there something I'm missing or doing wrong to make the project run on my local machine?

**Comment by CodeMongerrr** [comment]
for the client side install the dependencies using "npm i" and then "npm start" to start the client side app
for the backend again "npm i" in the directory and then "nodemon index.js" / "node index.js"

do these in 2 different terminals and run these commands in the right directory
